export const styles = {
    container: {
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
      padding: '16px',
      borderTop: '1px solid #e5e7eb',
      backgroundColor: 'white',
    },
    inputWrapper: {
      position: 'relative',
      flex: 1,
    },
    input: {
      width: '100%',
      padding: '10px 40px 10px 16px',
      borderRadius: '8px',
      border: '1px solid #e5e7eb',
      backgroundColor: 'white',
      color: '#111827',
      fontSize: '14px',
      outline: 'none',
    },
    inputDisabled: {
      opacity: 0.5,
      cursor: 'not-allowed',
    },
    enterIcon: {
      position: 'absolute',
      right: '12px',
      top: '50%',
      transform: 'translateY(-50%)',
      color: '#9ca3af',
    },
    actionsRow: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    uploadButtons: {
      display: 'flex',
      gap: '8px',
      position: 'relative',
    },
    iconButton: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '8px',
      borderRadius: '6px',
      color: '#6b7280',
      backgroundColor: 'transparent',
      border: 'none',
      cursor: 'pointer',
      transition: 'all 0.2s',
    },
    spinner: {
      width: '16px',
      height: '16px',
      border: '2px solid #e5e7eb',
      borderTop: '2px solid #3b82f6',
      borderRadius: '50%',
      animation: 'spin 1s linear infinite',
    },
  };