export const styles = {
  // ChatInput styles
  container: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "8px",
    borderTop: "1px solid #e5e7eb",
  },
  textareaContainer: {
    position: "relative",
    display: "flex",
    width: "100%",
  },
  textarea: {
    width: "100%",
    resize: "none",
    minHeight: "36px",
    maxHeight: "150px",
    padding: "8px 40px 8px 16px",
    borderRadius: "8px",
    border: "1px solid var(--vscode-input-border)",
    backgroundColor: "var(--vscode-input-background)",
    color: "var(--vscode-input-foreground)",
    fontSize: "12px",
    outline: "none",
    overflowY: "auto",
    lineHeight: "1.5",
    scrollbarWidth: "thin",
    scrollbarColor: "var(--vscode-scrollbarSlider-background) transparent",
  },
  sendButton: {
    position: "absolute",
    right: "8px",
    bottom: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px",
    background: "none",
    border: "none",
    cursor: "pointer",
    borderRadius: "4px",
    color: "var(--vscode-button-foreground)",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "var(--vscode-button-hoverBackground)",
    },
  },
  actionsRow: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },

  // FileSelector styles
  filesWrapper: {
    position: "relative",
  },
  filesContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "4px",
    padding: "4px",
    alignItems: "center",
  },
  fileTag: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "var(--vscode-button-secondaryBackground)",
    color: "var(--vscode-button-secondaryForeground)",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "12px",
  },
  removeButton: {
    marginLeft: "4px",
    border: "none",
    background: "none",
    color: "var(--vscode-button-secondaryForeground)",
    cursor: "pointer",
    padding: "0 4px",
    fontSize: "12px",
  },
  addButton: {
    display: "flex",
    alignItems: "center",
    padding: "2px 2px",
    backgroundColor: "transparent",
    border: "1px dashed var(--vscode-button-secondaryBackground)",
    borderRadius: "4px",
    cursor: "pointer",
    color: "var(--vscode-button-secondaryForeground)",
  },
  dropdown: {
    position: "absolute",
    bottom: "100%",
    left: 0,
    right: 0,
    backgroundColor: "var(--vscode-dropdown-background)",
    border: "1px solid var(--vscode-dropdown-border)",
    maxHeight: "300px",
    overflowY: "auto",
  },
  searchContainer: {
    padding: "8px",
    borderBottom: "1px solid var(--vscode-dropdown-border)",
    position: "sticky",
    top: 0,
    backgroundColor: "var(--vscode-dropdown-background)",
    zIndex: 1,
  },
  searchInput: {
    width: "100%",
    padding: "8px 12px",
    border: "1px solid var(--vscode-input-border)",
    borderRadius: "4px",
    fontSize: "12px",
    backgroundColor: "var(--vscode-input-background)",
    color: "var(--vscode-input-foreground)",
    outline: "none",
    "&:focus": {
      borderColor: "var(--vscode-focusBorder)",
    },
  },
  fileList: {
    margin: 0,
    padding: 0,
    listStyle: "none",
  },
  fileItem: {
    padding: "4px 8px",
    cursor: "pointer",
    fontSize: "12px",
    color: "var(--vscode-foreground)",
    "&:hover": {
      backgroundColor: "var(--vscode-list-hoverBackground)",
    },
  },

  // ModeSwitch styles
  modeSwitch: {
    display: "flex",
    gap: "8px",
  },
  modeButton: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "4px 8px",
    borderRadius: "4px",
    border: "none",
    cursor: "pointer",
    fontSize: "12px",
    transition: "all 0.2s",
  },
  activeMode: {
    backgroundColor: "var(--vscode-button-background)",
    color: "var(--vscode-button-foreground)",
  },
  inactiveMode: {
    backgroundColor: "transparent",
    color: "var(--vscode-foreground)",
  },

  // States
  disabled: {
    opacity: 0.5,
    cursor: "not-allowed",
    pointerEvents: "none",
  },
  inactive: {
    opacity: 0.3,
  },
};
