export const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "8px",
    borderTop: "1px solid #e5e7eb",
  },
  inputWrapper: {
    position: "relative",
    flex: 1,
  },
  textareaContainer: {
    position: "relative",
    display: "flex",
    width: "100%",
  },
  textarea: {
    width: "100%",
    resize: "none",
    minHeight: "36px",
    maxHeight: "150px",
    padding: "8px 40px 8px 16px", // Espacio para el botón
    borderRadius: "8px",
    border: "1px solid var(--vscode-input-border)",
    backgroundColor: "var(--vscode-input-background)",
    color: "var(--vscode-input-foreground)",
    fontSize: "12px",
    outline: "none",
    overflowY: "auto",
    lineHeight: "1.5",
    scrollbarWidth: "thin",
    scrollbarColor: "var(--vscode-scrollbarSlider-background) transparent",
  },
  sendButton: {
    position: "absolute",
    right: "8px",
    bottom: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px",
    background: "none",
    border: "none",
    cursor: "pointer",
    borderRadius: "4px",
    color: "var(--vscode-button-foreground)",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "var(--vscode-button-hoverBackground)",
    },
  },
  sendIcon: {
    width: "16px",
    height: "16px",
  },
  buttonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
    pointerEvents: "none",
  },
  buttonInactive: {
    opacity: 0.3,
  },
  inputDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  enterIcon: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#000",
  },
  actionsRow: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  uploadButtons: {
    display: "flex",
    gap: "8px",
    position: "relative",
  },
  iconButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px",
    borderRadius: "6px",
    color: "#6b7280",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  spinner: {
    width: "16px",
    height: "16px",
    border: "2px solid #e5e7eb",
    borderTop: "2px solid #3b82f6",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
};
